version: '3'
services:
    mongo:
        restart: always
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=maseh
            - MONGO_INITDB_ROOT_PASSWORD=shareef
    app:
        container_name: docker-node-mongo
        restart: always
        build: .
        ports:
            - '80:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        links:
            - mongo